baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

theme = 'AltitudeDark'

# Enable section-based menus
sectionPagesMenu = "main"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true